# Jekyll configuration
lsi: false
safe: true
source: ceruleancee.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Social info
navigation: True # show the navbar links
twitter: ceruleancee

theme: jekyll-theme-slate